export const MESSAGE = {
  SUCCESS: {},
  ERRORS: {
    AUTH: {
      INVALID_USER_USER_DELETED: 'INVALID_USER_USER_DELETED',
      UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
      CANNOT_VALIDATE_USER: 'CANNOT_VALIDATE_USER',
      CANNOT_VALIDATE_ADMIN: 'CANNOT_VALIDATE_ADMIN',
      EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
      RESET_CODE_VERIFICATION_FAILED: 'RESET_CODE_VERIFICATION_FAILED',
    },
    SYSTEM: {
      FAIL_TO_UPDATE_DATABASE: 'FAIL_TO_UPDATE_DATABASE',
      INVALID_DATA_FORMAT: 'INVALID_DATA_FORMAT',
      FAIL_TO_PUBLISH_MESSAGE: 'FAIL_TO_PUBLISH_MESSAGE',
    },
    USER: {
      // validation
      INVALID_USERNAME: 'INVALID_USERNAME',
      INVALID_PASSWORD: 'INVALID_PASSWORD',
      INVALID_EMAIL: 'INVALID_EMAIL',
      INVALID_ROLE: 'INVALID_ROLE',
      INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
      INVALID_QUOTE: 'INVALID_QUOTE',
      INVALID_ICON: 'INVALID_ICON',

      // CRUD
      USERNAME_ALREADY_USED: 'USERNAME_ALREADY_USED',
      EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
      FAIL_TO_CREATE_USER: 'FAIL_TO_CREATE_USER',
      FAIL_TO_UPDATE_USERINFO: 'FAIL_TO_UPDATE_USERINFO',
      FAIL_TO_UPDATE_EMAIL: 'FAIL_TO_UPDATE_EMAIL',
      FAIL_TO_UPDATE_PASSWORD: 'FAIL_TO_UPDATE_PASSWORD',
      FAIL_TO_VALIDATE_PASSWORD: 'FAIL_TO_VALIDATE_PASSWORD',
      FAIL_TO_DELETE_ACCOUNT: 'FAIL_TO_DELETE_ACCOUNT',

      USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
      USER_DOES_NOT_PROVIDE_EMAIL: 'USER_DOES_NOT_PROVIDE_EMAIL',
      USER_IS_DELETED: 'USER_IS_DELETED',
      ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',
    },
    UTIL: {
      HASH_PASSWORD_FAIL: 'HASH_PASSWORD_FAIL',
      CHECK_PASSWORD_FAIL: 'CHECK_PASSWORD_FAIL',
      USER_VALIDATION_FAIL: 'USER_VALIDATION_FAIL',
      UPLOAD_ICON_FAIL: 'UPLOAD_ICON_FAIL',
    },
    EMAIL_SERVICE: {
      FAIL_TO_SEND_EMAIL: 'FAIL_TO_SEND_EMAIL',
    },
  },
};
